- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push farrisreaktr/farris-devops-app:latest
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)
