trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'farrisreaktr/farris-devops-app'

steps:
- script: |
    docker build -t $(imageName) .
  displayName: 'Build Docker Image'

- script: |
    echo "Login to Docker Hub"
    docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
    docker push $(imageName)
  displayName: 'Push to Docker Hub'
